In [5]:
#1
import numpy as np
arr=np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [ ]:
#2
arr=np.zeros((4,6))
arr[2][2]=99
arr

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 99.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [ ]:
#3
arr=np.array([12,45,7,19,88,3,56,91,24,67])
print(arr[arr>50])

[88 56 91 67]


In [ ]:
#4
arr=np.eye(5)
arr=np.diag([10,20,30,40,50])
arr

array([[10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 40,  0],
       [ 0,  0,  0,  0, 50]])

In [ ]:
#5
x=np.arange(1,21).reshape(4,5)
print('1',x)
print('2',x[-2:])
print('3',x[:,3])
print('4',x[:3,:3])




1 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
2 [[11 12 13 14 15]
 [16 17 18 19 20]]
3 [ 4  9 14 19]
4 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [ ]:
#6
a=np.array([1,2,3,4])#1x4
b=np.array([[10],[20],[30]])#3x1
a+b
#we have 2 dimensions equal and there is one dimensions =1 so we can broadcasting add 1d array two times and sumation it

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [41]:
#7
data=np.array([150,220,90,300,180,45])
data1=(data-data.min())/(data.max()-data.min())
print(data1)


[0.41176471 0.68627451 0.17647059 1.         0.52941176 0.        ]


In [42]:
#8
data=np.array([150,220,90,300,180,45])
data1=(data-data.mean())/data.std()
print(data1)


[-0.16988961  0.66956492 -0.88942206  1.62894153  0.18987662 -1.42907141]


In [18]:
#9
mat=np.array([
    [4,8,1,12],
    [7,3,9,5],
    [11,2,6,10],
    [15,0,14,13]
]
)
#1
print(mat.mean(axis=1,keepdims=True))
#2
print(mat.sum(axis=0,keepdims=True))
#3
print("Max value",mat.max())
pos=np.unravel_index(mat.argmax(), mat.shape)
print("Position:",pos)



[[ 6.25]
 [ 6.  ]
 [ 7.25]
 [10.5 ]]
[[37 13 30 40]]
Max value 15
Position: (3, 0)


In [43]:
#10
arr=np.arange(36).reshape(3,4,3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [ ]:
#11
arr=np.arange(1,17).reshape(4,4)
print(arr)
print(arr.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [ ]:
#12
ages=np.array([23,45,19,34,28,51,17,39])
names=np.array(['Ali','Sara','Omar','Lina','Khaled','Nour','Yara','Hassan'])
names[(ages >= 20) & (ages <= 45)]

array(['Ali', 'Sara', 'Lina', 'Khaled', 'Hassan'], dtype='<U6')

In [8]:
#13
ages=np.array([23,45,19,34,28,51,17,39])
names=np.array(['Ali','Sara','Omar','Lina','Khaled','Nour','Yara','Hassan'])
ages[ages<20]=20
names[ages==20]

array(['Omar', 'Yara'], dtype='<U6')

In [54]:
#14
np.random.seed(123)
arr=np.random.randint(1,101,size=(6,6))
print(arr)

[[ 67  93  99  18  84  58]
 [ 87  98  97  48  74  33]
 [ 47  97  26  84  79  37]
 [ 97  81  69  50  56  68]
 [  3  85  40  67  85  48]
 [ 62  49   8 100  93  53]]


In [58]:
#15
arr=np.random.normal(100,15,10)
print(arr)

[ 99.11021829 109.98548699  98.02703326  62.93142249 111.5116785
  99.89412092 101.71936892  94.20313315 111.1183884  118.85037641]


In [ ]:
#16
colors=["red","blue","green","yellow","purple"]
print(np.random.choice(colors,size=3,replace=False))

['green' 'purple' 'blue']


In [ ]:
#17
arr=np.arange(1,21)
np.random.shuffle(arr)
print(arr)

[ 8 18 15  3  5 19 11  9 17 10 16  1  7 13  6  2  4 12 14 20]
